---
abstract: 'A general-purpose form handling API'
author:
  - 'Andrew Sterling Hanenkamp <hanenkamp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Form-Factory
requires:
  List::MoreUtils: 0.22
  Moose: 0.93
  Test::Able: 0.09
  Test::Able::Runner: 1.00
resources:
  repository: http://github.com/zostay/FormFactory
version: 0.019
